#:schema https://mago.carthage.software/1.29.0/schema.json
# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
version = "1"
php-version = "8.5.0"

[source]
workspace = "."
paths = ["src", "tests"]
includes = ["vendor"]
excludes = []

[source.glob]
literal-separator = true

[formatter]
preset = "pint"

[linter]
integrations = ["laravel", "pest"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }
no-boolean-flag-parameter = { enabled = false }
no-empty = { enabled = false }
too-many-methods = { enabled = false }

[analyzer]
plugins = []
excludes = ["tests/**/*.php"]
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = false
memoize-properties = true
check-throws = true
unchecked-exceptions = ["Error", "LogicException"]
unchecked-exception-classes = []
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
strict-array-index-existence = true
allow-array-truthy-operand = false
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true
trust-existence-checks = true
